<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930140110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_campus_name ON campus (name)');
        $this->addSql('CREATE TABLE classroom (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, classroom_type_id INT NOT NULL, campus_id INT NOT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_classroom_name ON classroom (name)');
        $this->addSql('CREATE INDEX IDX_497D309D4FBD4DBB ON classroom (classroom_type_id)');
        $this->addSql('CREATE INDEX IDX_497D309DAF5D55E1 ON classroom (campus_id)');
        $this->addSql('CREATE INDEX IDX_497D309DAE80F5DF ON classroom (department_id)');
        $this->addSql('CREATE TABLE classroom_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_classroomType_name ON classroom_type (name)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(25) DEFAULT NULL, account_id INT NOT NULL, teacher_id INT DEFAULT NULL, student_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT CHK_contact_owner CHECK ((teacher_id IS NOT NULL AND student_id IS NULL) OR (teacher_id IS NULL AND student_id IS NOT NULL))');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT CHK_contact_method CHECK (phone_number IS NOT NULL OR email IS NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C62E6389B6B5FBA ON contact (account_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C62E63841807E1D ON contact (teacher_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C62E638CB944F1A ON contact (student_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_email ON contact (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_phoneNumber ON contact (phone_number)');
        $this->addSql('CREATE TABLE day (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_day_name ON day (name)');
        $this->addSql('CREATE TABLE degree (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_degree_name ON degree (name)');
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, institute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD1DE18A5E237E06 ON department (name)');
        $this->addSql('CREATE INDEX IDX_CD1DE18A697B0F4C ON department (institute_id)');
        $this->addSql('CREATE TABLE foreign_university (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE institute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_institute_name ON institute (name)');
        $this->addSql('CREATE TABLE pair (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, classroom_id INT NOT NULL, day_id INT NOT NULL, students_group_id INT NOT NULL, teacher_id INT DEFAULT NULL, pair_number_id INT NOT NULL, pair_type_id INT NOT NULL, subject_id INT NOT NULL, week_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pair_teacher ON pair (teacher_id, pair_number_id, day_id, week_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pair_stud_group ON pair (students_group_id, pair_number_id, day_id, week_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pair_classroom ON pair (classroom_id, pair_number_id, day_id, week_id)');
        $this->addSql('CREATE INDEX IDX_95A1E696278D5A8 ON pair (classroom_id)');
        $this->addSql('CREATE INDEX IDX_95A1E699C24126 ON pair (day_id)');
        $this->addSql('CREATE INDEX IDX_95A1E69E29BBEF9 ON pair (students_group_id)');
        $this->addSql('CREATE INDEX IDX_95A1E6941807E1D ON pair (teacher_id)');
        $this->addSql('CREATE INDEX IDX_95A1E6965B36389 ON pair (pair_number_id)');
        $this->addSql('CREATE INDEX IDX_95A1E69E944780D ON pair (pair_type_id)');
        $this->addSql('CREATE INDEX IDX_95A1E6923EDC87 ON pair (subject_id)');
        $this->addSql('CREATE INDEX IDX_95A1E69C86F3B2F ON pair (week_id)');
        $this->addSql('CREATE TABLE pair_number (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pair_number SMALLINT NOT NULL, start TIME(0) WITHOUT TIME ZONE NOT NULL, finish TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pairNumber_number ON pair_number (pair_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pairNumber_start ON pair_number (start)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pairNumber_finish ON pair_number (finish)');
        $this->addSql('CREATE TABLE pair_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_pairType_name ON pair_type (name)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_name ON role (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_code ON role (code)');
        $this->addSql('CREATE TABLE speciality (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, institute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_speciality_name ON speciality (name)');
        $this->addSql('CREATE INDEX IDX_F3D7A08E697B0F4C ON speciality (institute_id)');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, birthdate DATE NOT NULL, students_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_student_name ON student (first_name, last_name, middle_name, birthdate)');
        $this->addSql('CREATE INDEX IDX_B723AF33E29BBEF9 ON student (students_group_id)');
        $this->addSql('CREATE TABLE students_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, course_num SMALLINT NOT NULL, group_num SMALLINT NOT NULL, speciality_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_studGroup ON students_group (course_num, group_num, speciality_id)');
        $this->addSql('CREATE INDEX IDX_61D323313B5A08D7 ON students_group (speciality_id)');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_subject_name ON subject (name)');
        $this->addSql('CREATE INDEX IDX_FBCE3E7AAE80F5DF ON subject (department_id)');
        $this->addSql('CREATE TABLE teacher (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(25) NOT NULL, email VARCHAR(255) DEFAULT NULL, birthdate DATE NOT NULL, department_id INT NOT NULL, degree_id INT NOT NULL, foreign_university_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_teacher ON teacher (first_name, last_name, middle_name, birthdate)');
        $this->addSql('CREATE INDEX IDX_B0F6A6D5AE80F5DF ON teacher (department_id)');
        $this->addSql('CREATE INDEX IDX_B0F6A6D5B35C5756 ON teacher (degree_id)');
        $this->addSql('CREATE INDEX IDX_B0F6A6D5BF10FC0E ON teacher (foreign_university_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, password VARCHAR(255) DEFAULT NULL, is_verified BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT CHK_user_verified_password CHECK (is_verified = FALSE OR password IS NOT NULL)');
        $this->addSql('CREATE INDEX IDX_8D93D649D60322AC ON "user" (role_id)');
        $this->addSql('CREATE TABLE user_verification_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, code_hash VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_103E78B49B6B5FBA ON user_verification_code (account_id)');
        $this->addSql('CREATE TABLE week (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_week_name ON week (name)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309D4FBD4DBB FOREIGN KEY (classroom_type_id) REFERENCES classroom_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309DAF5D55E1 FOREIGN KEY (campus_id) REFERENCES campus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309DAE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6389B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63841807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E696278D5A8 FOREIGN KEY (classroom_id) REFERENCES classroom (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E699C24126 FOREIGN KEY (day_id) REFERENCES day (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E69E29BBEF9 FOREIGN KEY (students_group_id) REFERENCES students_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E6941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E6965B36389 FOREIGN KEY (pair_number_id) REFERENCES pair_number (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E69E944780D FOREIGN KEY (pair_type_id) REFERENCES pair_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E6923EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pair ADD CONSTRAINT FK_95A1E69C86F3B2F FOREIGN KEY (week_id) REFERENCES week (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE speciality ADD CONSTRAINT FK_F3D7A08E697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33E29BBEF9 FOREIGN KEY (students_group_id) REFERENCES students_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE students_group ADD CONSTRAINT FK_61D323313B5A08D7 FOREIGN KEY (speciality_id) REFERENCES speciality (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7AAE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5B35C5756 FOREIGN KEY (degree_id) REFERENCES degree (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5BF10FC0E FOREIGN KEY (foreign_university_id) REFERENCES foreign_university (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_verification_code ADD CONSTRAINT FK_103E78B49B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE classroom DROP CONSTRAINT FK_497D309D4FBD4DBB');
        $this->addSql('ALTER TABLE classroom DROP CONSTRAINT FK_497D309DAF5D55E1');
        $this->addSql('ALTER TABLE classroom DROP CONSTRAINT FK_497D309DAE80F5DF');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6389B6B5FBA');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E63841807E1D');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638CB944F1A');
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A697B0F4C');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E696278D5A8');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E699C24126');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E69E29BBEF9');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E6941807E1D');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E6965B36389');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E69E944780D');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E6923EDC87');
        $this->addSql('ALTER TABLE pair DROP CONSTRAINT FK_95A1E69C86F3B2F');
        $this->addSql('ALTER TABLE speciality DROP CONSTRAINT FK_F3D7A08E697B0F4C');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33E29BBEF9');
        $this->addSql('ALTER TABLE students_group DROP CONSTRAINT FK_61D323313B5A08D7');
        $this->addSql('ALTER TABLE subject DROP CONSTRAINT FK_FBCE3E7AAE80F5DF');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5AE80F5DF');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5B35C5756');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5BF10FC0E');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE user_verification_code DROP CONSTRAINT FK_103E78B49B6B5FBA');
        $this->addSql('DROP TABLE campus');
        $this->addSql('DROP TABLE classroom');
        $this->addSql('DROP TABLE classroom_type');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE day');
        $this->addSql('DROP TABLE degree');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE foreign_university');
        $this->addSql('DROP TABLE institute');
        $this->addSql('DROP TABLE pair');
        $this->addSql('DROP TABLE pair_number');
        $this->addSql('DROP TABLE pair_type');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE speciality');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE students_group');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_verification_code');
        $this->addSql('DROP TABLE week');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
